//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInventory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Master
    {
        public string Item_ID { get; set; }
        public string Item { get; set; }
        public string Item_Description { get; set; }
        public string Unit { get; set; }
        public string C_Code { get; set; }
    
        public virtual Item_Category Item_Category { get; set; }
        public virtual UOM UOM { get; set; }
    }
}
