//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInventory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Notification_ID { get; set; }
        public string Notification_To { get; set; }
        public string Notification1 { get; set; }
        public bool Is_Read { get; set; }
        public string Notification_Type { get; set; }
    }
}
