//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInventory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int Id { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public int OrderId { get; set; }
        public int StockId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ApprovedBy { get; set; }
        public int Order_Line { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Order_Master Order_Master { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
