//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInventory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_Detail
    {
        public int POD_ID { get; set; }
        public int PO_ID { get; set; }
        public byte PO_Line { get; set; }
        public int Item_ID { get; set; }
        public int Qty { get; set; }
        public decimal Unit_Price { get; set; }
    
        public virtual PO_Header PO_Header { get; set; }
    }
}
