//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInventory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_Header
    {
        public string PO { get; set; }
        public string Supplier { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
    }
}
