//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInventory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_Line
    {
        public string PO { get; set; }
        public decimal PO_Line1 { get; set; }
        public string Item_ID { get; set; }
        public decimal Qty { get; set; }
        public decimal Unit_Price { get; set; }
    }
}
