//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInventory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string Trn_ID { get; set; }
        public string Trn_Type { get; set; }
        public string Loc_Code { get; set; }
        public string Service_ID { get; set; }
        public string Resource_ID { get; set; }
        public string Unit_ID { get; set; }
        public string Item_ID { get; set; }
        public decimal Qty { get; set; }
        public string Approver { get; set; }
        public string E_Approver { get; set; }
    }
}
