//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInventory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStock
    {
        public string ProductName { get; set; }
        public string Item_Name { get; set; }
        public string Location { get; set; }
        public int LineItem_ID { get; set; }
        public int Product_ID { get; set; }
        public decimal Qty { get; set; }
        public int Loc_ID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> WIP_Qty { get; set; }
        public Nullable<System.DateTime> Warranty_Expiry { get; set; }
        public Nullable<System.DateTime> Item_Expiry { get; set; }
    }
}
